name: priem_poliklinika
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  age_calculator: ^1.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  smooth_page_indicator: ^1.2.1
  supabase_flutter: ^2.9.0
  url_launcher: ^6.3.1

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
